name: Add new s3 bucket
on:
  workflow_dispatch:
    inputs:
      name:
        type: string
      region:
        type: string
      port_payload:
        required: true
        description: "Port's payload, including details for who triggered the action and general context (blueprint, run id, etc...)"
        type: string
env:
  NAME: ${{ inputs.name }}
  REGION: ${{ inputs.region }}

jobs:
  commit_tfvar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Parse inputs and create TFVar file
        run: |
          echo "bucket_name = \"$NAME\"" > s3-buckets/tfvars/$NAME.tfvar
          echo "region = \"$REGION\"" >> s3-buckets/tfvars/$NAME.tfvar

      - name: Commit TFVar file
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git checkout -b feature/add-$NAME-tfvar
          git add s3-buckets/tfvars/*.tfvar
          git commit -m "Add new TFVar file for $NAME"

      - name: Push branch
        run: git push origin feature/add-$NAME-tfvar

  create_pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create Pull Request
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh pr create --head feature/add-$NAME-tfvar --title "Add TFVar for $NAME" --body "This PR adds a new TFVar file for $NAME."
