name: Print Payload

on:
  workflow_dispatch:
    inputs: # keep empty to print any inputs
      port_payload:
        required: true
        description:
          Port's payload, including details for who triggered the action and
          general context (blueprint, run id, etc...)
        type: string

jobs:
  print_payload:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print payload
        run: |
          echo '${{ toJson(github.event.inputs) }}' | python .github/scripts/parse_json.py | jq
